languageCode = 'ja-jp'
#baseURL = 'https://miru-committee.github.io/miru2024/'
baseURL = 'http://ec2-54-238-219-28.ap-northeast-1.compute.amazonaws.com/miru2024/'
title = 'MIRU2024'
theme = "main"
defaultContentLanguage = 'ja'
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = "MIRUについて"
    weight = 1
    identifier = "about"

[[menu.main]]
    name = "プログラム編成方針"
    weight = 1
    parent = "about"
    url = "/about/program_policy/"

[[menu.main]]
    name = "選奨規定"
    weight = 2
    parent = "about"
    url = "/about/selection_criteria/"

[[menu.main]]
    name = "招待講演推薦"
    weight = 3
    parent = "about"
    url = "/about/call_for_invited_talk/"


[[menu.main]]
    name = "投稿"
    weight = 2
    identifier = "/submission/"
    url = "/submission/"

[[menu.main]]
    name = "参加登録"
    weight = 3
    identifier = "/registration/"
    url = "/registration/"

[[menu.main]]
    name = "現地参加"
    weight = 4
    identifier = "attend"

[[menu.main]]
    name = "託児室"
    weight = 1
    parent = "attend"
    url = "/attend/nursery/"


[[menu.main]]
    name = "プログラム"
    weight = 5
    identifier = "program"

[[menu.main]]
    name = "タイムテーブル"
    weight = 1
    parent = "program"
    url = "/program/timetable/"

[[menu.main]]
    name = "特別講演"
    weight = 2
    parent = "program"
    url = "/program/keynote/"

[[menu.main]]
    name = "チュートリアル"
    weight = 3
    parent = "program"
    url = "/program/tutorial/"

[[menu.main]]
    name = "ワークライフバランスイベント"
    weight = 4
    parent = "program"
    url = "https://sites.google.com/view/miru2024wlb/"

[[menu.main]]
    name = "インターナショナルイベント"
    weight = 5
    parent = "program"
    url = "https://sites.google.com/view/miru2024-internationallunch/"


[[menu.main]]
    name = "特別企画"
    weight = 6
    identifier = "special"

[[menu.main]]
    name = "メンターシッププログラム"
    weight = 1
    parent = "special"
    url = "https://sites.google.com/view/prmu-rmp/miru"

[[menu.main]]
    name = "若手プログラム"
    weight = 2
    parent = "special"
    url = "https://sites.google.com/view/miru2024wakate/"

[[menu.main]]
    name = "朝ランの会"
    weight = 3
    parent = "special"
    url = "https://ohym.org/MIRU2024_Running.html"


[[menu.main]]
    name = "スポンサー"
    weight = 7
    identifier = "/sponsor/"
    url = "/sponsor/"


[[languages.en.menu.main]]
    name = "About MIRU"
    weight = 1
    identifier = "about"

[[languages.en.menu.main]]
    name = "Program policy"
    weight = 1
    parent = "about"
    url = "/en/about/program_policy/"

[[languages.en.menu.main]]
    name = "Award Selection Criteria"
    weight = 2
    parent = "about"
    url = "/en/about/selection_criteria/"

[[languages.en.menu.main]]
    name = "Call for Invited Talk"
    weight = 3
    parent = "about"
    url = "/en/about/call_for_invited_talk/"



[[languages.en.menu.main]]
    name = "Submission"
    weight = 2
    identifier = "/en/submission/"
    url = "/en/submission/"

[[languages.en.menu.main]]
    name = "Registration"
    weight = 3
    identifier = "/en/registration/"
    url = "/en/registration/"

[[languages.en.menu.main]]
    name = "Attend"
    weight = 4
    identifier = "attend"

[[languages.en.menu.main]]
    name = "Nursery room"
    weight = 1
    parent = "attend"
    url = "/en/attend/nursery/"


[[languages.en.menu.main]]
    name = "Program"
    weight = 5
    identifier = "program"

[[languages.en.menu.main]]
    name = "Timetable"
    weight = 1
    parent = "program"
    url = "/en/program/timetable/"

[[languages.en.menu.main]]
    name = "Keynotes"
    weight = 2
    parent = "program"
    url = "/en/program/keynote/"

[[languages.en.menu.main]]
    name = "Tutorials"
    weight = 3
    parent = "program"
    url = "/en/program/tutorial/"


[[languages.en.menu.main]]
    name = "Work life balance event"
    weight = 4
    parent = "program"
    url = "https://sites.google.com/view/miru2024wlb/english"

[[languages.en.menu.main]]
    name = "International event"
    weight = 5
    parent = "program"
    url = "https://sites.google.com/view/miru2024-internationallunch/"


[[languages.en.menu.main]]
    name = "Special events"
    weight = 6
    identifier = "special"

[[languages.en.menu.main]]
    name = "Mentorship program"
    weight = 1
    parent = "special"
    url = "https://sites.google.com/view/prmu-rmp/miru"

[[languages.en.menu.main]]
    name = "Wakate program"
    weight = 2
    parent = "special"
    url = "https://sites.google.com/view/miru2024wakate/"

[[languages.en.menu.main]]
    name = "Morning Run Club"
    weight = 3
    parent = "special"
    url = "https://ohym.org/MIRU2024_Running.html"



[[languages.en.menu.main]]
    name = "Sponsor"
    weight = 7
    identifier = "/en/sponsor/"
    url = "/en/sponsor/"

[languages]
[languages.ja]
title = "MIRU 2024"
weight = 1
[languages.ja.params]
flag = '<svg width="36" height="36" xmlns="http://www.w3.org/2000/svg" id="flag-icon-css-us" viewBox="0 0 640 480"><g fill-rule="evenodd"><g stroke-width="1pt"><path fill="#bd3d44" d="M0 0h972.8v39.4H0zm0 78.8h972.8v39.4H0zm0 78.7h972.8V197H0zm0 78.8h972.8v39.4H0zm0 78.8h972.8v39.4H0zm0 78.7h972.8v39.4H0zm0 78.8h972.8V512H0z" transform="scale(.9375)"/><path fill="#fff" d="M0 39.4h972.8v39.4H0zm0 78.8h972.8v39.3H0zm0 78.7h972.8v39.4H0zm0 78.8h972.8v39.4H0zm0 78.8h972.8v39.4H0zm0 78.7h972.8v39.4H0z" transform="scale(.9375)"/></g><path fill="#192f5d" d="M0 0h389.1v275.7H0z" transform="scale(.9375)"/><path fill="#fff" d="M32.4 11.8L36 22.7h11.4l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.3-6.7H29zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 11-9.2-6.8-9.3 6.7 3.5-10.9-9.2-6.7h11.4zm64.8 0l3.6 10.9H177l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.3-6.7h11.5zm64.9 0l3.5 10.9H242l-9.3 6.7 3.6 11-9.3-6.8-9.3 6.7 3.6-10.9-9.3-6.7h11.4zm64.8 0l3.6 10.9h11.4l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.2-6.7h11.4zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.6 11-9.3-6.8-9.3 6.7 3.6-10.9-9.3-6.7h11.5zM64.9 39.4l3.5 10.9h11.5L70.6 57 74 67.9l-9-6.7-9.3 6.7L59 57l-9-6.7h11.4zm64.8 0l3.6 10.9h11.4l-9.3 6.7 3.6 10.9-9.3-6.7-9.3 6.7L124 57l-9.3-6.7h11.5zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 10.9-9.2-6.7-9.3 6.7 3.5-10.9-9.2-6.7H191zm64.8 0l3.6 10.9h11.4l-9.3 6.7 3.6 10.9-9.3-6.7-9.2 6.7 3.5-10.9-9.3-6.7H256zm64.9 0l3.5 10.9h11.5L330 57l3.5 10.9-9.2-6.7-9.3 6.7 3.5-10.9-9.2-6.7h11.4zM32.4 66.9L36 78h11.4l-9.2 6.7 3.5 10.9-9.3-6.8-9.2 6.8 3.5-11-9.3-6.7H29zm64.9 0l3.5 11h11.5l-9.3 6.7 3.5 10.9-9.2-6.8-9.3 6.8 3.5-11-9.2-6.7h11.4zm64.8 0l3.6 11H177l-9.2 6.7 3.5 10.9-9.3-6.8-9.2 6.8 3.5-11-9.3-6.7h11.5zm64.9 0l3.5 11H242l-9.3 6.7 3.6 10.9-9.3-6.8-9.3 6.8 3.6-11-9.3-6.7h11.4zm64.8 0l3.6 11h11.4l-9.2 6.7 3.5 10.9-9.3-6.8-9.2 6.8 3.5-11-9.2-6.7h11.4zm64.9 0l3.5 11h11.5l-9.3 6.7 3.6 10.9-9.3-6.8-9.3 6.8 3.6-11-9.3-6.7h11.5zM64.9 94.5l3.5 10.9h11.5l-9.3 6.7 3.5 11-9.2-6.8-9.3 6.7 3.5-10.9-9.2-6.7h11.4zm64.8 0l3.6 10.9h11.4l-9.3 6.7 3.6 11-9.3-6.8-9.3 6.7 3.6-10.9-9.3-6.7h11.5zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 11-9.2-6.8-9.3 6.7 3.5-10.9-9.2-6.7H191zm64.8 0l3.6 10.9h11.4l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.3-6.7H256zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 11-9.2-6.8-9.3 6.7 3.5-10.9-9.2-6.7h11.4zM32.4 122.1L36 133h11.4l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.3-6.7H29zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 10.9-9.2-6.7-9.3 6.7 3.5-10.9-9.2-6.7h11.4zm64.8 0l3.6 10.9H177l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.3-6.7h11.5zm64.9 0l3.5 10.9H242l-9.3 6.7 3.6 11-9.3-6.8-9.3 6.7 3.6-10.9-9.3-6.7h11.4zm64.8 0l3.6 10.9h11.4l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.2-6.7h11.4zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.6 11-9.3-6.8-9.3 6.7 3.6-10.9-9.3-6.7h11.5zM64.9 149.7l3.5 10.9h11.5l-9.3 6.7 3.5 10.9-9.2-6.8-9.3 6.8 3.5-11-9.2-6.7h11.4zm64.8 0l3.6 10.9h11.4l-9.3 6.7 3.6 10.9-9.3-6.8-9.3 6.8 3.6-11-9.3-6.7h11.5zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 10.9-9.2-6.8-9.3 6.8 3.5-11-9.2-6.7H191zm64.8 0l3.6 10.9h11.4l-9.2 6.7 3.5 10.9-9.3-6.8-9.2 6.8 3.5-11-9.3-6.7H256zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 10.9-9.2-6.8-9.3 6.8 3.5-11-9.2-6.7h11.4zM32.4 177.2l3.6 11h11.4l-9.2 6.7 3.5 10.8-9.3-6.7-9.2 6.7 3.5-10.9-9.3-6.7H29zm64.9 0l3.5 11h11.5l-9.3 6.7 3.6 10.8-9.3-6.7-9.3 6.7 3.6-10.9-9.3-6.7h11.4zm64.8 0l3.6 11H177l-9.2 6.7 3.5 10.8-9.3-6.7-9.2 6.7 3.5-10.9-9.3-6.7h11.5zm64.9 0l3.5 11H242l-9.3 6.7 3.6 10.8-9.3-6.7-9.3 6.7 3.6-10.9-9.3-6.7h11.4zm64.8 0l3.6 11h11.4l-9.2 6.7 3.5 10.8-9.3-6.7-9.2 6.7 3.5-10.9-9.2-6.7h11.4zm64.9 0l3.5 11h11.5l-9.3 6.7 3.6 10.8-9.3-6.7-9.3 6.7 3.6-10.9-9.3-6.7h11.5zM64.9 204.8l3.5 10.9h11.5l-9.3 6.7 3.5 11-9.2-6.8-9.3 6.7 3.5-10.9-9.2-6.7h11.4zm64.8 0l3.6 10.9h11.4l-9.3 6.7 3.6 11-9.3-6.8-9.3 6.7 3.6-10.9-9.3-6.7h11.5zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 11-9.2-6.8-9.3 6.7 3.5-10.9-9.2-6.7H191zm64.8 0l3.6 10.9h11.4l-9.2 6.7 3.5 11-9.3-6.8-9.2 6.7 3.5-10.9-9.3-6.7H256zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.5 11-9.2-6.8-9.3 6.7 3.5-10.9-9.2-6.7h11.4zM32.4 232.4l3.6 10.9h11.4l-9.2 6.7 3.5 10.9-9.3-6.7-9.2 6.7 3.5-11-9.3-6.7H29zm64.9 0l3.5 10.9h11.5L103 250l3.6 10.9-9.3-6.7-9.3 6.7 3.6-11-9.3-6.7h11.4zm64.8 0l3.6 10.9H177l-9 6.7 3.5 10.9-9.3-6.7-9.2 6.7 3.5-11-9.3-6.7h11.5zm64.9 0l3.5 10.9H242l-9.3 6.7 3.6 10.9-9.3-6.7-9.3 6.7 3.6-11-9.3-6.7h11.4zm64.8 0l3.6 10.9h11.4l-9.2 6.7 3.5 10.9-9.3-6.7-9.2 6.7 3.5-11-9.2-6.7h11.4zm64.9 0l3.5 10.9h11.5l-9.3 6.7 3.6 10.9-9.3-6.7-9.3 6.7 3.6-11-9.3-6.7h11.5z" transform="scale(.9375)"/></g></svg>'

[languages.en]
title = "MIRU 2024"
weight = 1
[languages.en.params]
flag = '<svg width="36" height="36" xmlns="http://www.w3.org/2000/svg" id="flag-icon-css-jp" viewBox="0 0 640 480"><defs><clipPath id="jp-a"><path fill-opacity=".7" d="M-88 32h640v480H-88z"/></clipPath></defs><g fill-rule="evenodd" stroke-width="1pt" clip-path="url(#jp-a)" transform="translate(88 -32)"><path fill="#fff" d="M-128 32h720v480h-720z"/><circle cx="523.1" cy="344.1" r="194.9" fill="#d30000" transform="translate(-168.4 8.6) scale(.76554)"/></g></svg>'
